parameters:
  SolutionBaseName:
  BuildConfiguration:
  TargetProjects: 'src/**/*.csproj'

jobs:
- job: CodeBuild
  pool:
    name: SLD Build pool
  variables:
  - group: BUILD Management Resources
  - name: SolutionBaseName
    value: SFA.DAS.Payments.FundingSource
  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml


   # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.Application/SFA.DAS.Payments.FundingSource.Application.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.Application/SFA.DAS.Payments.FundingSource.Application.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.Application/SFA.DAS.Payments.FundingSource.Application.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.Domain/SFA.DAS.Payments.FundingSource.Domain.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.Domain/SFA.DAS.Payments.FundingSource.Domain.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.Domain/SFA.DAS.Payments.FundingSource.Domain.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.LevyAccountBalanceService/SFA.DAS.Payments.FundingSource.LevyAccountBalanceService.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.LevyAccountBalanceService/SFA.DAS.Payments.FundingSource.LevyAccountBalanceService.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.LevyAccountBalanceService/SFA.DAS.Payments.FundingSource.LevyAccountBalanceService.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.LevyFundedProxyService/SFA.DAS.Payments.FundingSource.LevyFundedProxyService.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.LevyFundedProxyService/SFA.DAS.Payments.FundingSource.LevyFundedProxyService.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.LevyFundedProxyService/SFA.DAS.Payments.FundingSource.LevyFundedProxyService.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.LevyFundedService/SFA.DAS.Payments.FundingSource.LevyFundedService.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.LevyFundedService/SFA.DAS.Payments.FundingSource.LevyFundedService.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.LevyFundedService/SFA.DAS.Payments.FundingSource.LevyFundedService.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.FundingSource.NonLevyFundedService/SFA.DAS.Payments.FundingSource.NonLevyFundedService.csproj
  - task: DotNetCoreCLI@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.NonLevyFundedService/SFA.DAS.Payments.FundingSource.NonLevyFundedService.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.NonLevyFundedService/SFA.DAS.Payments.FundingSource.NonLevyFundedService.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'




  # task: NuGetCommand@2 - src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: NuGetCommand@2 - src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: NuGetCommand@2 - src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj
  - task: NuGetCommand@2
    displayName: Restore - src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'



  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.Application/SFA.DAS.Payments.FundingSource.Application.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.Domain/SFA.DAS.Payments.FundingSource.Domain.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.LevyAccountBalanceService/SFA.DAS.Payments.FundingSource.LevyAccountBalanceService.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.LevyFundedProxyService/SFA.DAS.Payments.FundingSource.LevyFundedProxyService.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.LevyFundedService/SFA.DAS.Payments.FundingSource.LevyFundedService.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces/SFA.DAS.Payments.FundingSource.LevyFundedService.Interfaces.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.FundingSource.NonLevyFundedService/SFA.DAS.Payments.FundingSource.NonLevyFundedService.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'



  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true
  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true
      
  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true



      
  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: drop

  - template: /azure-pipelines-templates/build/step/nuget-pack.yml
    parameters:
      DotNetStandardPackagesToPack: |
        src/SFA.DAS.Payments.FundingSource.Messages/SFA.DAS.Payments.FundingSource.Messages.csproj;
        src/SFA.DAS.Payments.FundingSource.Model/SFA.DAS.Payments.FundingSource.Model.csproj;
        src/SFA.DAS.Payments.FundingSource.Messages.Internal/SFA.DAS.Payments.FundingSource.Messages.Internal.csproj;